import os
from dotenv import load_dotenv

load_dotenv()

AZURE_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")

EMBEDDING_API_KEY = os.getenv("AZURE_EMBEDDING_API_KEY")
EMBEDDING_ENDPOINT = os.getenv("AZURE_EMBEDDING_ENDPOINT")
EMBEDDING_API_VERSION = os.getenv("AZURE_EMBEDDING_API_VERSION")
EMBEDDING_DEPLOYMENT_NAME = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
storage_name = os.getenv("AZURE_STORAGE_ACCOUNT_NAME")
